# Required settings
# -----------------
token = ${TOKEN}
mainServerId = 1471198850923368660
inboxServerId = 1471198850923368660
logChannelId = 1471581658137235651

# Common settings
# ----------------------------------
prefix = ?
inboxServerPermission = manageMessages
status = Message me for help!
responseMessage = Ticket opened. A staff will soon respond.

# Add new options below this line:
# ----------------------------------
